name = "cf-notion-worker"
type = "webpack"
webpack_config = "webpack.config.js"

account_id = "bdf98396791787c8083597e478acd516"

workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-25"
