name = "cf-notion-worker"
main = 'src/index.js'
account_id = "bdf98396791787c8083597e478acd516"
workers_dev = true
compatibility_date = "2022-09-27"

[env.production]
workers_dev = false
route = "https://worker.alekspetrov.com/*"
zone_id = "a69833b312105822037c5c51269c3db7"